hard_tabs = true
max_width = 80
newline_style = "Unix"
use_field_init_shorthand = true
<<<<<<< HEAD
use_try_shorthand = true
=======
use_try_shorthand = true
edition = "2018"
>>>>>>> f60ddd8fd15002f83e02c8f28aeb4b9fb078ba18
